import type { Locale } from "./locale";

const ko = {
  brand: "오늘 장날",
  tagline: "전국 5일장·전통시장 일정 지도",
  homeLabel: "오늘 장날 홈",
  allMarkets: "전체",
  today: "오늘",
  week: "이번 주",
  weekend: "주말",
  chooseDate: "날짜 선택",
  date: "날짜",
  filterLabel: "시장 검색 및 날짜 필터",
  searchLabel: "시장명 또는 지역 검색",
  searchPlaceholder: "시장명 또는 지역을 검색하세요",
  clearSearch: "검색어 지우기",
  dateRange: "날짜 범위",
  allMarketHeading: "전체 전통시장",
  selectedDateHeading: "선택한 날짜에 운영하는 시장",
  marketDayHeading: "선택한 기간의 장날 시장",
  nationwide: "전국",
  loadingMarkets: "시장 정보를 불러오는 중입니다.",
  loadFailed: "시장 정보를 불러오지 못했어요",
  tryAgainLater: "잠시 후 다시 시도해 주세요.",
  retry: "다시 시도",
  listLabel: "시장 목록",
  noResults: "조건에 맞는 시장이 없어요",
  noResultsHelp: "지역 이름을 줄이거나 다른 날짜를 골라보세요.",
  resetFilters: "필터 초기화",
  resultsLabel: "검색된 시장",
  scheduleLabel: "운영 일정",
  operates: "운영",
  marketDay: "장날",
  addressMissing: "주소 정보 없음",
  locationMissing: "위치 확인 필요",
  mapLabel: "전국 전통시장 지도",
  mapLoading: "전국 장날 지도를 펼치는 중",
  mapFallbackTitle: "지도 없이도 시장을 찾을 수 있어요",
  mapFallbackBody: "지도 연결을 확인하는 동안 왼쪽 목록에서 시장과 장날을 모두 탐색할 수 있습니다.",
  currentLocation: "현재 위치",
  locationUnavailable: "이 브라우저에서는 현재 위치를 사용할 수 없어요.",
  locating: "현재 위치를 확인하고 있어요.",
  located: "현재 위치로 이동했어요.",
  locationDenied: "위치 권한이 필요해요. 브라우저 설정에서 허용한 뒤 다시 시도해 주세요.",
  locationFailed: "현재 위치를 확인하지 못했어요. 잠시 후 다시 시도해 주세요.",
  mapPreview: "미리보기",
  viewDetail: "상세 보기",
  mapLegend: "시장명 · 운영 일정",
  sheetHandle: "시트 손잡이",
  expandPreview: "미리보기 펼치기",
  openList: "목록 열기",
  close: "닫기",
  backToList: "목록으로",
  enlargeList: "목록 크게 보기",
  viewMap: "지도 보기",
  allResults: "전체 시장 결과",
  selectedMarketPrompt: "지도 핀이나 시장 목록을 선택하면",
  selectedMarketHelp: "다음 장날을 자세히 보여드려요.",
  closeDetail: "시장 상세 닫기",
  nextMarketDay: "다음 장날",
  dailySchedule: "매일 운영",
  scheduleUnconfirmed: "운영 일정 확인 필요",
  operatingToday: "오늘 운영",
  marketDayToday: "오늘 장날",
  nextSevenDays: "오늘부터 7일",
  visitInfo: "방문 정보",
  address: "주소",
  phone: "전화",
  parking: "주차",
  parkingAvailable: "주차 가능",
  noParking: "주차장 없음",
  confirmNeeded: "확인 필요",
  noInformation: "정보 없음",
  map: "지도",
  source: "정보 출처",
  sourceDate: "데이터 기준일",
  sourceDateMissing: "확인일 정보 없음",
  reportCorrection: "정보가 다른가요? 수정 제보",
  share: "공유하기",
  copySucceeded: "링크를 복사했어요",
  copyFailed: "링크를 복사하지 못했어요",
  onnuri: "온누리상품권",
  report: "불편 신고",
  about: "서비스 소개",
  privacy: "개인정보 처리방침",
  terms: "이용약관",
  dataPolicy: "데이터 출처와 편집 기준",
  reportInfo: "정보 수정 제보",
  menu: "보조 메뉴",
  openMenu: "메뉴 열기",
  closeMenu: "메뉴 닫기",
  installTitle: "홈 화면에 추가",
  installDescription: "장날을 앱처럼 빠르게 확인할 수 있어요.",
  installIosGuide: "Safari의 공유 버튼을 누른 뒤 ‘홈 화면에 추가’를 선택하세요.",
  add: "추가하기",
  addHow: "추가 방법",
  dismissInstall: "14일 동안 닫기",
} satisfies Record<string, string>;

const en: typeof ko = {
  brand: "K Market Day",
  tagline: "Traditional market days across Korea",
  homeLabel: "K Market Day home",
  allMarkets: "All markets",
  today: "Market days today",
  week: "Next 7 days",
  weekend: "This weekend",
  chooseDate: "Choose date",
  date: "Date",
  filterLabel: "Search markets and choose a date",
  searchLabel: "Search a region in English or a market name in Korean",
  searchPlaceholder: "Region in English or market in Korean",
  clearSearch: "Clear search",
  dateRange: "Date range",
  allMarketHeading: "All traditional markets",
  selectedDateHeading: "Markets on your chosen date",
  marketDayHeading: "Market days in the selected period",
  nationwide: "Across Korea",
  loadingMarkets: "Loading market information.",
  loadFailed: "Could not load market information",
  tryAgainLater: "Please try again.",
  retry: "Try again",
  listLabel: "Market list",
  noResults: "No markets match these filters",
  noResultsHelp: "Try a province such as Seoul or Jeju, or choose another date.",
  resetFilters: "Reset filters",
  resultsLabel: "Market search results",
  scheduleLabel: "Schedule",
  operates: "Schedule",
  marketDay: "Market day",
  addressMissing: "Address unavailable",
  locationMissing: "Location needs confirmation",
  mapLabel: "Traditional market map of Korea",
  mapLoading: "Loading the market map",
  mapFallbackTitle: "You can still use the market list",
  mapFallbackBody: "The map is unavailable. Browse the list for markets and market days.",
  currentLocation: "Current location",
  locationUnavailable: "This browser cannot access your location.",
  locating: "Finding your location.",
  located: "Moved to your location.",
  locationDenied: "Location permission is needed. Allow it in your browser settings and try again.",
  locationFailed: "Could not find your location. Please try again.",
  mapPreview: "Preview",
  viewDetail: "View details",
  mapLegend: "Market name · schedule",
  sheetHandle: "Sheet handle",
  expandPreview: "Expand preview",
  openList: "Open list",
  close: "Close",
  backToList: "Back to list",
  enlargeList: "Expand list",
  viewMap: "View map",
  allResults: "All market results",
  selectedMarketPrompt: "Select a market on the map or in the list",
  selectedMarketHelp: "to see its next market day.",
  closeDetail: "Close market details",
  nextMarketDay: "Next market day",
  dailySchedule: "Regular daily schedule",
  scheduleUnconfirmed: "Schedule not confirmed",
  operatingToday: "Daily schedule",
  marketDayToday: "Market day today",
  nextSevenDays: "Next 7 days",
  visitInfo: "Visitor information",
  address: "Address",
  phone: "Phone",
  parking: "Parking",
  parkingAvailable: "Parking available",
  noParking: "No parking listed",
  confirmNeeded: "Check before visiting",
  noInformation: "Information unavailable",
  map: "Map",
  source: "Information source",
  sourceDate: "Data reference date",
  sourceDateMissing: "Verification date unavailable",
  reportCorrection: "Report an issue (Korean)",
  share: "Share",
  copySucceeded: "Link copied",
  copyFailed: "Could not copy the link",
  onnuri: "Onnuri gift certificates (Korean)",
  report: "Report an issue (Korean)",
  about: "About (Korean)",
  privacy: "Privacy policy (Korean)",
  terms: "Terms of service (Korean)",
  dataPolicy: "Data sources (Korean)",
  reportInfo: "Report a correction (Korean)",
  menu: "Site menu",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  installTitle: "Add to home screen",
  installDescription: "Open market days quickly like an app.",
  installIosGuide: "In Safari, tap Share and then Add to Home Screen.",
  add: "Add",
  addHow: "How to add",
  dismissInstall: "Dismiss for 14 days",
};

export function getUiCopy(locale: Locale): typeof ko {
  return locale === "en" ? en : ko;
}
